# Permalinks
permalink:        pretty

# Setup
url:              lixianfeng.cc

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          https://li-xianfeng.github.io

title:            Ervj

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  见贤思齐

# The tags listed as entries in the sidebar
sidebar_tags:     [前端, Others]

# Fallback image and color if not overwritten for tag or post
image:            ./public/img/nap.jpg
color:            '#A85641'

author:
  name:           'Li Xianfeng'
  github:         li-xianfeng
  photo:          

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    李显锋，2015毕业于四川大学，至今工作于58赶集集团

theme: jekyll-theme-time-machine